Cwe789
fkie-cad/cwe_checker pull request #347
Opened 2022-07-25 14:15 UTC by m-rtz

Implemented CWE789: Memory Allocation with Excessive Size Value

The check uses thresholds for stack memory allocations and heap memory allocation defined in config.json. For the stack allocation case, every assignment onto the stackpointer is checked, if it exceeds the threshold.
For the heap memory case the functions xmalloc, malloc, realloc and calloc are predefined and their arguments are checked if they exceed the threshold.

2022-07-25 14:18 UTC, m-rtz commented
If an warning is generated for the stack allocation case, it seems like a new warning is generated on every following assignment onto the stack pointer, including calls. This might lead to a large amount of warnings.

2022-07-26 11:27 UTC, Enkelmann requested changes
The check looks good!

Apart from reducing the number of duplicates for stack-related CWE warnings this check also needs an acceptance check!

Have you tried this on some firmware binaries? I fear that the standard `heap_threshold` in the `config.json` might be too small. The `stack_threshold` on the other hand should be smaller in my opinion. But we should test that on some real world examples before deciding the standard threshold values.

2022-07-26 11:27 UTC, Enkelmann commented on src/cwe_checker_lib/src/checkers/cwe_789.rs
> +                    .unwrap()
You have already stored the result of `analysis_results.pointer_inference.unwrap()` in the `pir` variable.

2022-07-26 11:27 UTC, Enkelmann commented on src/cwe_checker_lib/src/checkers/cwe_789.rs
> +    cwe_warnings.dedup();
This `dedup()` call unfortunately does not help us here. One possible way to only produce at most one stack-related CWE warning per function is to add a `break` (or `continue` the outer loop) after the first CWE warning is generated for a function.

2022-07-28 07:51 UTC, m-rtz commented on src/cwe_checker_lib/src/checkers/cwe_789.rs
> +        nmeb.bin_op(BinOpType::IntMult, &size);
Good Hint! Using this I discovered the same bug in CWE190.

2022-08-04 10:09 UTC, m-rtz commented
> The check looks good!
> 
> Apart from reducing the number of duplicates for stack-related CWE warnings this check also needs an acceptance check!
> 
> Have you tried this on some firmware binaries? I fear that the standard `heap_threshold` in the `config.json` might be too small. The `stack_threshold` on the other hand should be smaller in my opinion. But we should test that on some real world examples before deciding the standard threshold values.

I evaluated the check on some firmware binaries and the current values: 1MB for heap allocations and 7500B for stack allocation seems to be a starting point for this check.

2022-08-04 11:23 UTC, merged